# SalesForce DataConnections
sfdc.consumer.k=3MVG9nSH73I5aFNhKr09lRm3EWv7CwIsq75mIZDRiuDPcLBR7XxKlg8kKUTzzo80mh0pbcf3mtt41ZuUU6_uy
sfdc.consumer.s=80E15CBBD0A587660B64FFC0F5BF170116C06767798EA96C677DC6FFB229517F
sfdc.username=amarillo17cyl@gmail.com
sfdc.paswd=![Qm5eM99J0u2Z3ScH98jqnCzxMnFzCwn/]
sfdc.token=![+I9KKDTdb0FTMVZOK7RHLAWJWQfymf6U1uSFTh7/eek=]
sfdc.loginurl=https://login.salesforce.com/services/Soap/u/64.0
sfdc.url=https://login.salesforce.com/services/Soap/u/64.0